language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  SECRET_TOKEN=test
deploy:
  provider: heroku
  api_key:
    secure: IqiMpwj9uSOiraMRdjEn4KM+n84urNS7YCwN0M0hn8fTlqU9ux1nKw3WS9x34w1G05hWm5IMO1x2lU52WKDcJ8P9TbFOt3tjOg9FDT9yOeSCDe1ti589Tna+iEgjDpC13vFNdInpV4cd7nXKptOLBJWjxgqW/suinnefGJqi+FA=
  app: nouse-travis
  on:
    rvm: 2.0.0
    repo: kimihito/nouse-travis
