language: ruby
rvm:
- 2.0.0
env:
  SECRET_TOKEN=test
deploy:
  provider: heroku
  api_key:
    secure: eDZ9p6++U3XrksLvn8ESNp5SzHEaSU55Aa9JpKUnJikmJtCvO5PH354KUaDJlUHcDpzHt70/eaZwz6HtYCyVxxiP3PZCBXxLVFDEa5+Y2tpEFG21YYzyeKZUK7YuOX3iO+zrSD5S79oYlxfBECbV4ruACMUZ+IvCnydqvbVYxNg=
  on:
    rvm: 2.0.0
