language: ruby
rvm:
- 1.9.3
- 2.0.0
env: SECRET_TOKEN=test
deploy:
  provider: heroku
  api_key:
    secure: WnAtVfTGMSA3lLtG6Dgds65bzQTcyhCXmWVi6DYa30bMKzM4IHwio5OW5LSuqkADEke8XSeudRagtwduv55AJ4dutk974lxg28NAbU5tVYvjo/w6nIXZXG6lbtHAl0VIy8mXUAtkEG7aeGqcZPShjcK9eM3lMLJ+4pGJ3XNj/7g=
  app: nouse-travis
  on:
    rvm: 2.0.0
    repo: kimihito/nouse-travis
